removed obsolete argument

diff --git a/init.d/d7-gateway b/init.d/d7-gateway
--- a/init.d/d7-gateway
+++ b/init.d/d7-gateway
@@ -11,14 +11,17 @@
 # Description:       Starts oss7-thingsboard-gateway
 ### END INIT INFO
 
-# If you want a command to always run, put it here
+if [  ! -e /etc/d7-gateway/d7-gateway.conf ]; then
+   echo "/etc/d7-gateway/d7-gateway.conf not found."
+   exit 2
+fi
 
 # Carry out specific functions when asked to by the system
 case "$1" in
   start)
     echo "Starting D7 gateway"
     cd /home/pi/oss7-thingsboard-gateway/
-    PYTHONPATH="lib/pyd7a" python2 gateway.py -d /dev/ttyACM0 -l /var/log/d7-gateway.log &
+    PYTHONPATH="lib/pyd7a" python2 gateway.py -l /var/log/d7-gateway.log @/etc/d7-gateway/d7-gateway.conf &
     ;;
   stop)
     echo "Stopping D7 gateway"
